version: '3'
services:
  client: 
    build:
      context: ./client
      dockerfile: ./client/Dockerfile
    ports:
      - "8080:3000"
    container_name: my-web-app
  server: 
    build:
      context: ./server
      dockerfile: ./server/Dockerfile
    ports:
      - "8080:3001"
    container_name: my-web-app