version: '3'
services:
  nodejs_app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/client/src/app
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
