version: '3'
services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - node-network
  server: 
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    container_name: sever-app
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/group2
    depends_on:
      - mongodb
    networks:
      - node-network

volumes:
  dbdata6:

networks:
  node-network:
    driver: bridge
